name: mpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - xarray
  - pyvista
  - pythreejs
  - jupyterlab
  - ipython
  - scipy
  - numpy 
  - ipyvtklink
  - shapely
