name: mpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - xarray
  - pyvista
  - ipygany
  - jupyterlab
  - ipython
  - scipy
  - ipython
  - numpy 
